"""
Authentication and Security Module for Sentio 2.0
Provides JWT authentication, password hashing, and role-based access control
"""

from .auth_service import AuthService, get_auth_service
from .models import (
    User,
    UserRole,
    UserInDB,
    TokenData,
    UserCreate,
    UserLogin,
    Token,
    UserUpdate,
    PasswordChange,
    RefreshToken,
    TokenPair,
    RefreshTokenRequest,
    MFAEnrollment,
    MFAVerification,
    MFALogin,
    Session,
    AuditLogEntry,
    PasswordResetRequest,
    PasswordResetConfirm,
    OAuth2Provider,
    OAuth2Login,
)
from .security import (
    get_password_hash,
    verify_password,
    create_access_token,
    verify_token,
    create_refresh_token,
    generate_reset_token,
    generate_session_id,
    generate_mfa_secret,
    verify_mfa_token,
    generate_qr_code,
)

__all__ = [
    "AuthService",
    "get_auth_service",
    "User",
    "UserRole",
    "UserInDB",
    "TokenData",
    "UserCreate",
    "UserLogin",
    "Token",
    "UserUpdate",
    "PasswordChange",
    "RefreshToken",
    "TokenPair",
    "RefreshTokenRequest",
    "MFAEnrollment",
    "MFAVerification",
    "MFALogin",
    "Session",
    "AuditLogEntry",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "OAuth2Provider",
    "OAuth2Login",
    "get_password_hash",
    "verify_password",
    "create_access_token",
    "verify_token",
    "create_refresh_token",
    "generate_reset_token",
    "generate_session_id",
    "generate_mfa_secret",
    "verify_mfa_token",
    "generate_qr_code",
]
